---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: k3s-dep-test
    image: rockylinux:9
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
