---
galaxy_info:
  role_name: k3s_dependencies
  author: k3s-ansible-playbook
  description: Install k3s system dependencies on RHEL/Rocky Linux 9
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - kubernetes
    - k3s
