---

# Provision the cluster
- name: K3s Deployment
  become: true
  gather_facts: true
  hosts: kube_cluster
  max_fail_percentage: 0
  roles:
    - name: hardening
      tags: hardening
      when: hardening_enabled is defined and hardening_enabled == false
    - name: k3s-dependencies
      tags: k3s,dependencies,prep
    - name: k3s-deploy
      tags: k3s,deploy

...
