---

- name: Gather the service facts
  ansible.builtin.service_facts:

- name: Disable service kdump
  ansible.builtin.systemd:
    name: kdump.service
    enabled: false
    state: stopped
    masked: true
  when: '"kdump.service" in ansible_facts.services'

- name: Install modprobe to disable filesystems
  ansible.builtin.package:
    name: '{{ modprobe_package }}'
    state: 'present'

- name: Check if efi is installed
  ansible.builtin.stat:
    path: "/sys/firmware/efi"
  register: efi_installed

- name: Remove vfat from fs-list if efi is used
  ansible.builtin.set_fact:
    os_unused_filesystems: "{{ os_unused_filesystems | difference('vfat') }}"
  when:
    - efi_installed.stat.isdir is defined
    - efi_installed.stat.isdir

- name: Remove used filesystems from fs-list
  ansible.builtin.set_fact:
    os_unused_filesystems: "{{ os_unused_filesystems | difference(ansible_mounts | map(attribute='fstype') | list) }}"
  when: not ((ansible_facts.os_family in ['Oracle Linux', 'RedHat']) and ansible_facts.distribution_major_version < '7')

- name: Disable unused modules
  ansible.builtin.template:
    src: 'modprobe_modules.j2'
    dest: '/etc/modprobe.d/blacklist-modules.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Disable unused filesystems
  ansible.builtin.template:
    src: 'modprobe_filesystems.j2'
    dest: '/etc/modprobe.d/blacklist-filesystems.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'

...
