---
# hardening
#
#
- name: Retrieve package facts
  package_facts:
    manager: "auto"

- name: Retrieve service facts
  service_facts:

# STIG 010220
- name: NSA 2.3.3.5 Upgrade Password Hashing Algorithm to SHA-512
  template:
    src: 'libuser.conf.j2'
    dest: '/etc/libuser.conf'
    mode: '0640'
    owner: 'root'
    group: 'root'
  when:
    - "'libuser' in ansible_facts.packages"

- name: Remove unwanted packages
  package:
    name: "{{ unwanted_pkg }}"
    state: absent

- name: Install wanted packages
  package:
    name: "{{ wanted_pkg }}"
    state: present

- name: Disable unwanted services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  delay: 3
  register: result
  retries: 3
  until: result is not failed
  when: "'{{ item }}' in ansible_facts.services"
  with_items: "{{ unwanted_services }}"

- import_tasks: package_manager.yml
- import_tasks: crontab.yml
- import_tasks: limits.yml
- import_tasks: mounts.yml
- import_tasks: ssh.yml
- import_tasks: auditd.yml
- import_tasks: kernel_modules.yml
- import_tasks: kernel_hardening.yml
- import_tasks: minimize_access.yml

...
