---
# hardening

- name: Retrieve package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Retrieve service facts
  ansible.builtin.service_facts:

# STIG 010220
- name: NSA 2.3.3.5 Upgrade Password Hashing Algorithm to SHA-512
  ansible.builtin.template:
    src: 'libuser.conf.j2'
    dest: '/etc/libuser.conf'
    mode: '0640'
    owner: 'root'
    group: 'root'
  when:
    - "'libuser' in ansible_facts.packages"

- name: Remove unwanted packages
  ansible.builtin.package:
    name: "{{ unwanted_pkg }}"
    state: absent

- name: Install wanted packages
  ansible.builtin.package:
    name: "{{ wanted_pkg }}"
    state: present

- name: Disable unwanted services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  delay: 3
  register: result
  retries: 3
  until: result is not failed
  when: "item in ansible_facts.services"
  with_items: "{{ unwanted_services }}"

- ansible.builtin.import_tasks: package_manager.yml
- ansible.builtin.import_tasks: crontab.yml
- ansible.builtin.import_tasks: limits.yml
- ansible.builtin.import_tasks: mounts.yml
- ansible.builtin.import_tasks: ssh.yml
- ansible.builtin.import_tasks: auditd.yml
- ansible.builtin.import_tasks: kernel_modules.yml
- ansible.builtin.import_tasks: kernel_hardening.yml
- ansible.builtin.import_tasks: minimize_access.yml

...
