---
arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  i386: i386
  ppc64le: ppc64le

arch: "{{ arch_mapping[ansible_facts['architecture']] | default('amd64') }}"

# defaults file for k3s-deploy
#
ingress_hostname: "{{ cluster_external_ip }}.nip.io"

k3s_version: v1.32.2+k3s1
k3s_binary_path: /usr/local/bin
kubectl_cmd: "{{ k3s_binary_path }}/k3s kubectl"

cluster_external_ip: "{{ ansible_host }}"
# Change to "none" to disable WireGuard and use VXLAN instead
# https://docs.k3s.io/networking/basic-network-options
flannel_backend: wireguard-native
bind_address: "{{ ansible_facts['ansible_' ~ (internal_interface | replace('-', '_'))]['ipv4']['address'] | default('0.0.0.0') }}"
advertise_address: "{{ ansible_facts['ansible_' ~ (internal_interface | replace('-', '_'))]['ipv4']['address'] | default(ansible_host) }}"
cluster_cidr: 10.43.0.0/16
service_cidr: 10.44.0.0/16

kubevip_enabled: true
kubevip_version: v1.1.2
kubevip_cloud_provider_version: v0.0.12
kubevip_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
kubevip_vip_address: ""
kubevip_external_ip_range: "{{ groups['kube_node'] | default([]) | map('extract', hostvars, 'ansible_host') | map('regex_replace', '$', '/32') | join(',') }}"
kubevip_internal_ip_range: ""

dashboard_enabled: true
portainer_version: "2.39.2"
portainer_ingress_host: "portainer.{{ cluster_external_ip }}.nip.io"
portainer_ingress_class: traefik

openebs_storage_enabled: true
openebs_version: 2.8.0

kubeless_enabled: false

falco_security_enabled: true
falco_sidekick_slack: ""
falco_sidekick_slack_priority: "warning"
falco_sidekick_poddelete_minimumpriority: "notice"
### Possible customizations
# falco_sidekick_alertmanager
# falco_sidekick_alertmanager_priority
# falco_sidekick_discord
# falco_sidekick_discord_priority
# falco_sidekick_googlechat
# falco_sidekick_googlechat_priority
# falco_sidekick_mattermost
# falco_sidekick_mattermost_priority
# falco_sidekick_poddelete_minimumpriority
# falco_sidekick_rocketchat
# falco_sidekick_rocketchat_priority
# falco_sidekick_slack
# falco_sidekick_slack_priority
# falco_sidekick_teams
# falco_sidekick_teams_priority
#####

# Retry tuning
pod_ready_retries: 60
pod_ready_delay: 10

protected_files:
    - /etc/falco/token
    - /etc/k3s-encryption.yaml
    - /etc/systemd/system/k3s-agent.service
    - /etc/systemd/system/k3s-server.service
    - /usr/lib/systemd/system/falco.service
    - /usr/lib/systemd/system/rescue.service
    - /var/lib/rancher/audit/audit-policy.yaml
    - /var/lib/rancher/audit/webhook-config.yaml

...
